apiVersion: v1
kind: ConfigMap
metadata:
  name: nzen-iot-client-test-config
data:
  config.properties: |
    mqtt.broker.url=192.168.0.74:1883
    mqtt.client.id=accelerometer-subscriber
    mqtt.topic=iot/accelerometer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzen-iot-client-test-deployment
  labels:
    app: nzen-iot-client-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nnzen-iot-client-test
  template:
    metadata:
      labels:
        app: nzen-iot-client-test
    spec:
      containers:
        - name: nzen-iot-client-test
          image: 44ce789b-kr1-registry.container.nhncloud.com/container-platform-registry/nzen-iot-client-test:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /root/config.properties
              subPath: config.properties
          env:
            - name: PROFILE
              value: "local"
      imagePullSecrets:
        - name: ncr-secret
      volumes:
        - name: config-volume
          configMap:
            name: nzen-iot-client-test-config

